
var checkWord = function (word) {

  var match = getName();

  if (word === "CHEAT") alert(match);
  if (word === "FLYNN") alert("Happy easter!!");

  if (names.every(x => x.name !== word)) return null;

  var result = [];

  for(var i=0; i<word.length; i++) {
    if (word[i] === match[i])
      // Match!
      result.push(2);
    else if (match.split("").every(x => x !== word[i])) {
      // Nope :(
      result.push(0);
    }
    else {
      // Could be elsewhere in word - handle multiple
      var upToThisPoint = word.substring(0, i).split("").filter(x => x === word[i]).length;

      // Exclude exact matches
      var total = match.split("").filter((x,j) => x === word[i] && match[j] !== word[j]).length;

      if (upToThisPoint >= total)
        result.push(0);
      else
        result.push(1)
    }
  }

  // Second pass - if matched elsewhere

  return result;
};

var getName = function() {
    // Days from day 0
    var ms = new Date() - new Date("2022-04-08T00:00");
    var day = Math.floor(ms / 1000 / 60 / 60 / 24);
  
    return names[day].name;  
};

var names = [
  { name: 'AISHA', sex: 'g' },
  { name: 'CASEY', sex: 'b' },
  { name: 'IDRIS', sex: 'b' },
  { name: 'PEGGY', sex: 'g' },
  { name: 'AMARI', sex: 'b' },
  { name: 'LILLY', sex: 'g' },
  { name: 'TALIA', sex: 'g' },
  { name: 'BETTY', sex: 'g' },
  { name: 'GRACE', sex: 'g' },
  { name: 'PIXIE', sex: 'g' },
  { name: 'INAYA', sex: 'g' },
  { name: 'ROBIN', sex: 'g' },
  { name: 'MARWA', sex: 'g' },
  { name: 'MAISY', sex: 'g' },
  { name: 'JULIA', sex: 'g' },
  { name: 'EADIE', sex: 'g' },
  { name: 'MONTY', sex: 'b' },
  { name: 'SYEDA', sex: 'g' },
  { name: 'PIPER', sex: 'g' },
  { name: 'ALINA', sex: 'g' },
  { name: 'HARRY', sex: 'b' },
  { name: 'SOFIA', sex: 'g' },
  { name: 'INDIA', sex: 'g' },
  { name: 'RILEY', sex: 'g' },
  { name: 'INDIE', sex: 'g' },
  { name: 'AYDEN', sex: 'b' },
  { name: 'ALBIE', sex: 'b' },
  { name: 'MARIA', sex: 'g' },
  { name: 'MILES', sex: 'b' },
  { name: 'SONNY', sex: 'b' },
  { name: 'AARAV', sex: 'b' },
  { name: 'JAMIE', sex: 'b' },
  { name: 'WOODY', sex: 'b' },
  { name: 'AGNES', sex: 'g' },
  { name: 'CAIRO', sex: 'b' },
  { name: 'PEARL', sex: 'g' },
  { name: 'ATLAS', sex: 'b' },
  { name: 'LACEY', sex: 'g' },
  { name: 'AHMAD', sex: 'b' },
  { name: 'NELLY', sex: 'g' },
  { name: 'ESMAE', sex: 'g' },
  { name: 'CHLOE', sex: 'g' },
  { name: 'AYAAN', sex: 'b' },
  { name: 'MALIK', sex: 'b' },
  { name: 'NAOMI', sex: 'g' },
  { name: 'AIDEN', sex: 'b' },
  { name: 'RUFUS', sex: 'b' },
  { name: 'NORAH', sex: 'g' },
  { name: 'MOLLY', sex: 'g' },
  { name: 'MAEVE', sex: 'g' },
  { name: 'AVERY', sex: 'g' },
  { name: 'SARAH', sex: 'g' },
  { name: 'ORSON', sex: 'b' },
  { name: 'MASON', sex: 'b' },
  { name: 'HOLLY', sex: 'g' },
  { name: 'ANAIS', sex: 'g' },
  { name: 'RAYAN', sex: 'b' },
  { name: 'OSCAR', sex: 'b' },
  { name: 'YAHYA', sex: 'b' },
  { name: 'TYLER', sex: 'b' },
  { name: 'LEWIS', sex: 'b' },
  { name: 'NIAMH', sex: 'g' },
  { name: 'LUCIE', sex: 'g' },
  { name: 'NANCY', sex: 'g' },
  { name: 'DOLLY', sex: 'g' },
  { name: 'KAIRO', sex: 'b' },
  { name: 'LAURA', sex: 'g' },
  { name: 'ALANA', sex: 'g' },
  { name: 'KEVIN', sex: 'b' },
  { name: 'BOBBY', sex: 'b' },
  { name: 'EDITH', sex: 'g' },
  { name: 'FREYA', sex: 'g' },
  { name: 'ELENA', sex: 'g' },
  { name: 'LUCAS', sex: 'b' },
  { name: 'ELSIE', sex: 'g' },
  { name: 'BLAKE', sex: 'b' },
  { name: 'AZAAN', sex: 'b' },
  { name: 'HENRY', sex: 'b' },
  { name: 'BETSY', sex: 'g' },
  { name: 'MABEL', sex: 'g' },
  { name: 'AHMED', sex: 'b' },
  { name: 'ALIZA', sex: 'g' },
  { name: 'KAYLA', sex: 'g' },
  { name: 'MILEY', sex: 'g' },
  { name: 'HALLE', sex: 'g' },
  { name: 'FILIP', sex: 'b' },
  { name: 'HAMZA', sex: 'b' },
  { name: 'ELIAS', sex: 'b' },
  { name: 'HARIS', sex: 'b' },
  { name: 'ANGUS', sex: 'b' },
  { name: 'BRODY', sex: 'b' },
  { name: 'YUSRA', sex: 'g' },
  { name: 'BRUNO', sex: 'b' },
  { name: 'WYATT', sex: 'b' },
  { name: 'JOSIE', sex: 'g' },
  { name: 'ARYAN', sex: 'b' },
  { name: 'AMINA', sex: 'g' },
  { name: 'ANGEL', sex: 'g' },
  { name: 'ROBYN', sex: 'g' },
  { name: 'RILEY', sex: 'b' },
  { name: 'MIRHA', sex: 'g' },
  { name: 'HANIA', sex: 'g' },
  { name: 'EMILY', sex: 'g' },
  { name: 'LEILA', sex: 'g' },
  { name: 'ROBIN', sex: 'b' },
  { name: 'JESSE', sex: 'b' },
  { name: 'LUKAS', sex: 'b' },
  { name: 'RONAN', sex: 'b' },
  { name: 'LAILA', sex: 'g' },
  { name: 'NYLAH', sex: 'g' },
  { name: 'RIVER', sex: 'b' },
  { name: 'SEREN', sex: 'g' },
  { name: 'LOGAN', sex: 'b' },
  { name: 'ANAYA', sex: 'g' },
  { name: 'FRANK', sex: 'b' },
  { name: 'MATEI', sex: 'b' },
  { name: 'EMMIE', sex: 'g' },
  { name: 'FLEUR', sex: 'g' },
  { name: 'PENNY', sex: 'g' },
  { name: 'MICAH', sex: 'b' },
  { name: 'AMIRA', sex: 'g' },
  { name: 'HAZEL', sex: 'g' },
  { name: 'RUBEN', sex: 'b' },
  { name: 'LILAH', sex: 'g' },
  { name: 'QUINN', sex: 'b' },
  { name: 'ALAYA', sex: 'g' },
  { name: 'ELIZA', sex: 'g' },
  { name: 'CONOR', sex: 'b' },
  { name: 'ELLIE', sex: 'g' },
  { name: 'KEIRA', sex: 'g' },
  { name: 'LAYLA', sex: 'g' },
  { name: 'OLLIE', sex: 'b' },
  { name: 'LUCIA', sex: 'g' },
  { name: 'DAVID', sex: 'b' },
  { name: 'REEVA', sex: 'g' },
  { name: 'COHEN', sex: 'b' },
  { name: 'YUNUS', sex: 'b' },
  { name: 'ARIYA', sex: 'g' },
  { name: 'LIBBY', sex: 'g' },
  { name: 'SADIE', sex: 'g' },
  { name: 'ROMEO', sex: 'b' },
  { name: 'ROSIE', sex: 'g' },
  { name: 'MEGAN', sex: 'g' },
  { name: 'AMBER', sex: 'g' },
  { name: 'DENIS', sex: 'b' },
  { name: 'AOIFE', sex: 'g' },
  { name: 'HONEY', sex: 'g' },
  { name: 'OSKAR', sex: 'b' },
  { name: 'ELISE', sex: 'g' },
  { name: 'LEYLA', sex: 'g' },
  { name: 'ASHER', sex: 'b' },
  { name: 'REIGN', sex: 'b' },
  { name: 'PETER', sex: 'b' },
  { name: 'LYDIA', sex: 'g' },
  { name: 'HEIDI', sex: 'g' },
  { name: 'LEXIE', sex: 'g' },
  { name: 'COREY', sex: 'b' },
  { name: 'JIMMY', sex: 'b' },
  { name: 'MACIE', sex: 'g' },
  { name: 'ELISA', sex: 'g' },
  { name: 'QUINN', sex: 'g' },
  { name: 'ZAHRA', sex: 'g' },
  { name: 'DIANA', sex: 'g' },
  { name: 'ALAIA', sex: 'g' },
  { name: 'BILAL', sex: 'b' },
  { name: 'MAEVA', sex: 'g' },
  { name: 'MILAN', sex: 'b' },
  { name: 'OSIAN', sex: 'b' },
  { name: 'RIVER', sex: 'g' },
  { name: 'AMARA', sex: 'g' },
  { name: 'EFFIE', sex: 'g' },
  { name: 'ROWAN', sex: 'b' },
  { name: 'PIPPA', sex: 'g' },
  { name: 'ARHAM', sex: 'b' },
  { name: 'DAISY', sex: 'g' },
  { name: 'AARON', sex: 'b' },
  { name: 'JONAH', sex: 'b' },
  { name: 'ZOFIA', sex: 'g' },
  { name: 'JASON', sex: 'b' },
  { name: 'ERICA', sex: 'g' },
  { name: 'JACOB', sex: 'b' },
  { name: 'IMAAN', sex: 'g' },
  { name: 'ZAYAN', sex: 'b' },
  { name: 'ISSAC', sex: 'b' },
  { name: 'CLARA', sex: 'g' },
  { name: 'JAMES', sex: 'b' },
  { name: 'ISAAC', sex: 'b' },
  { name: 'DARIA', sex: 'g' },
  { name: 'SKYLA', sex: 'g' },
  { name: 'TILLY', sex: 'g' },
  { name: 'HAFSA', sex: 'g' },
  { name: 'DARCY', sex: 'g' },
  { name: 'FAITH', sex: 'g' },
  { name: 'BELLE', sex: 'g' },
  { name: 'KIARA', sex: 'g' },
  { name: 'FLYNN', sex: 'b' },
  { name: 'JAXON', sex: 'b' },
  { name: 'COLBY', sex: 'b' },
  { name: 'MATEO', sex: 'b' },
  { name: 'OLIVE', sex: 'g' },
  { name: 'FLORA', sex: 'g' },
  { name: 'ARJUN', sex: 'b' },
  { name: 'BELLA', sex: 'g' },
  { name: 'HANNA', sex: 'g' },
  { name: 'KALEB', sex: 'b' },
  { name: 'TOMMY', sex: 'b' },
  { name: 'BODHI', sex: 'b' },
  { name: 'CHASE', sex: 'b' },
  { name: 'ERNIE', sex: 'b' },
  { name: 'ELLIS', sex: 'b' },
  { name: 'ROHAN', sex: 'b' },
  { name: 'ALFIE', sex: 'b' },
  { name: 'EDDIE', sex: 'b' },
  { name: 'ANNIE', sex: 'g' },
  { name: 'APRIL', sex: 'g' },
  { name: 'POPPY', sex: 'g' },
  { name: 'PERCY', sex: 'b' },
  { name: 'LOUIS', sex: 'b' },
  { name: 'ETHAN', sex: 'b' },
  { name: 'YUSUF', sex: 'b' },
  { name: 'LOUIE', sex: 'b' },
  { name: 'TEDDY', sex: 'b' },
  { name: 'CALEB', sex: 'b' },
  { name: 'JAKUB', sex: 'b' },
  { name: 'ABDUL', sex: 'b' },
  { name: 'FELIX', sex: 'b' },
  { name: 'KATIE', sex: 'g' },
  { name: 'AYMAN', sex: 'b' },
  { name: 'AIZAH', sex: 'g' },
  { name: 'AMAYA', sex: 'g' },
  { name: 'LENNY', sex: 'b' },
  { name: 'NADIA', sex: 'g' },
  { name: 'ILYAS', sex: 'b' },
  { name: 'PAIGE', sex: 'g' },
  { name: 'AAYAT', sex: 'g' },
  { name: 'AIYLA', sex: 'g' },
  { name: 'ROMAN', sex: 'b' },
  { name: 'FFION', sex: 'g' },
  { name: 'MYLES', sex: 'b' },
  { name: 'ALICE', sex: 'g' },
  { name: 'DYLAN', sex: 'b' },
  { name: 'AIDAN', sex: 'b' },
  { name: 'BILLY', sex: 'b' },
  { name: 'POLLY', sex: 'g' },
  { name: 'RALPH', sex: 'b' },
  { name: 'HARRI', sex: 'b' },
  { name: 'ROCCO', sex: 'b' },
  { name: 'KIAAN', sex: 'b' },
  { name: 'DANNY', sex: 'b' }
];

export default {
  checkWord: checkWord,
  getName: getName,
}